### PR TITLE
Handle completed subcollections

### PR DESCRIPTION
**Pull request by rafelafrance**
Handling completed subcollections via a metadata change. Unfortunately, it requires a pull request.

### CODE REVIEW

**Comment by parrish** [comment]
I'm confused about the intent.

If your goal is to exclude completed collections from the [Herbarium page](http://www.notesfromnature.org/#/archivegroup/SERNEC), why not filter groups by state? (`when group.state isnt 'complete'`)

Removing the collection name is pretty kludgey -- it also still leaves the completed USF collection on that page.

**Comment by rafelafrance** [comment]
Now that I know that that is an option, I'll see what I can do here.

**Comment by rafelafrance** [comment]
We don't really have test data for completed subcollections. All of my tests involved rigged (heavily mocked) data.

**Comment by parrish** [comment]
Sorry, one more change required.

Add `'state'` to the list of attributes on [the model](https://github.com/rafelafrance/notesFromNature/blob/master/app/models/archive.coffee#L13).  (It's a stupid Spine thing)

**Pull request merged**
