### PR TITLE
Add calbug expeditions collection

### PR DESCRIPTION
**Pull request by rafelafrance**
This looks right but we should verify that we're pulling images for the correct collection and that we're writing transcripts to the correct collection.

### CODE REVIEW

**Comment by robgur** [comment]
Awesome to see this.  Would like to test before it is just POOP available
on NFN.  Can you PLEASE let me know ASAP if this does go live so we can
quick test it, and i can get a blog post out about this new Expedition.  We
have it ready to go.  Darren, might be cool to try drumming up some
publicity on this maybe?  Its a neat thing to move towards these
expeditions, which we are going to build out in the neat future much more
fully! :)

Best, Rob

p.s. --- would be GREAT if we could get this up ASAP (today???)

**Comment by chrissnyder** [comment]
:+1:

**Comment by chrissnyder** [comment]
@robgur This has been deployed to the live site, with 15,416 images in the collection. All seems well with a brief glance.

**Comment by robgur** [comment]
Awesome. Can we put a "DONE" or some other way to denote that old CalBug is
"out" of images?

**Comment by poboyski** [comment]
I just entered a few specimens on the CalBug Expeditions site to test it
out. Seems to work fine. Nice work getting this up!

The only issue I noticed is that the black bar that gives the filename (eg.
EMEC12345 Genus species) says "undefined undefined".

Pete

------------------------------------------------------------
Dr. Peter T Oboyski
Collections Manager & Curatorial Supervisor
Essig Museum of Entomology
1170 Valley Life Science Building
University of California, Berkeley

mailing address:
1101 VLSB, #4780
Berkeley, CA 94720

http://nature.berkeley.edu/~poboyski/
http://essig.berkeley.edu

essig.museum@gmail.com
510.643.0804 (work phone)
510.847.0360 (cell phone)
--------------------------------------------------------------

**Pull request merged**
