### PR TITLE
Adding zoom for calbug and fixing minor GUI issues

### PR DESCRIPTION
**Pull request by rafelafrance**

### CODE REVIEW

**Comment by chrissnyder** [comment]
Calbug interface works like a charm.

Request for the future, could you either list the changes made out in the PR description or separate the commits out to atomic units of work? Since we lack a test suite (ugh) it's a bit hard to see what changed to test things out.

**Comment by rafelafrance** [comment]
Can do
On Jul 13, 2015 8:25 PM, "Chris Snyder" <notifications@github.com> wrote:

Merged #367 <https://github.com/zooniverse/notesFromNature/pull/367>.

—
Reply to this email directly or view it on GitHub
<https://github.com/zooniverse/notesFromNature/pull/367#event-354913232>.

**Comment by robgur** [comment]
Rafe, the change has had an unintended side-effect, noted below (I've
confirmed it too).  Can we fix this?

Just a small quality of life suggestion. The recent change that brought
zoom in/out to Calbug is great, but the change also now seems to force the
user to manually click in the box before typing in data. If this feature
could be closer to what it was a few days ago (being able to immediately
type data and tab between elements w/o clicking), I think it would be a
small quality of life improvement for some of us.

**Comment by rafelafrance** [comment]
Will do

**Pull request merged**
